version: '3'
services:
    zoo1:
        image: zookeeper
        restart: always
        container_name: zoo1
        hostname: zoo1
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
            ZOO_STANDALONE_ENABLED: "false"
            ZOO_4LW_COMMANDS_WHITELIST: "*"
    
    zoo2:
        image: zookeeper
        restart: always
        container_name: zoo2
        hostname: zoo2
        ports:
          - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
            ZOO_STANDALONE_ENABLED: "false"
            ZOO_4LW_COMMANDS_WHITELIST: "*"
    
    zoo3:
        image: zookeeper
        restart: always
        container_name: zoo3
        hostname: zoo3
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
            ZOO_STANDALONE_ENABLED: "false"
            ZOO_4LW_COMMANDS_WHITELIST: "*"
    
    kafka1:
        image: wurstmeister/kafka
        container_name: kafka1
        hostname: kafka1
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
            KAFKA_LISTENERS: "INTERNAL://kafka1:9092,EXTERNAL://kafka1:32001"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:9092,EXTERNAL://localhost:32001"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
        depends_on:
            - zoo1
            - zoo2
            - zoo3
        ports:
            - 32001:32001
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    
    kafka2:
        image: wurstmeister/kafka
        container_name: kafka2
        hostname: kafka2
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
            KAFKA_LISTENERS: "INTERNAL://kafka2:9092,EXTERNAL://kafka2:32002"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka2:9092,EXTERNAL://localhost:32002"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
        depends_on:
            - zoo1
            - zoo2
            - zoo3
        ports:
            - 32002:32002
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    
    kafka3:
        image: wurstmeister/kafka
        container_name: kafka3
        hostname: kafka3
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
            KAFKA_LISTENERS: "INTERNAL://kafka3:9092,EXTERNAL://kafka3:32003"
            KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka3:9092,EXTERNAL://localhost:32003"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
        depends_on:
            - zoo1
            - zoo2
            - zoo3
        ports:
            - 32003:32003
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock